import type {
  Issue,
  FlashAlert,
  FeedItem,
  CommunityPulse,
  UserProfile,
  CityMood,
  PredictiveInsight,
} from "./types";

export const mockPulse: CommunityPulse = {
  overall: 84,
  categories: [
    { name: "Roads", score: 91, icon: "🛣" },
    { name: "Lighting", score: 82, icon: "💡" },
    { name: "Water", score: 68, icon: "💧" },
    { name: "Waste", score: 75, icon: "🗑" },
    { name: "Drainage", score: 79, icon: "🌊" },
    { name: "Safety", score: 88, icon: "🛡" },
  ],
};

export const mockFeed: FeedItem[] = [
  {
    id: "f1",
    icon: "⚠",
    text: "Water issue verified in Sector 12",
    timestamp: "2 min ago",
    category: "water",
  },
  {
    id: "f2",
    icon: "⚡",
    text: "Streetlight fixed on MG Road",
    timestamp: "8 min ago",
    category: "lighting",
  },
  {
    id: "f3",
    icon: "🕳",
    text: "New pothole reported near City Mall",
    timestamp: "15 min ago",
    category: "road_damage",
  },
  {
    id: "f4",
    icon: "🗑",
    text: "5 citizens marked waste issue resolved",
    timestamp: "22 min ago",
    category: "waste",
  },
  {
    id: "f5",
    icon: "💧",
    text: "Water supply restored in Block A",
    timestamp: "30 min ago",
    category: "water",
  },
  {
    id: "f6",
    icon: "🛡",
    text: "Broken railing reported at Park Street",
    timestamp: "45 min ago",
    category: "safety",
  },
  {
    id: "f7",
    icon: "RD",
    text: "Drain cleaned near Metro Gate 2",
    timestamp: "52 min ago",
    category: "drainage",
  },
  {
    id: "f8",
    icon: "NO",
    text: "Noise complaint verified near Market Square",
    timestamp: "1 hr ago",
    category: "noise",
  },
  {
    id: "f9",
    icon: "LT",
    text: "Two new streetlight reports added in Sector 8",
    timestamp: "1 hr ago",
    category: "lighting",
  },
];

export const mockAlerts: FlashAlert[] = [
  {
    id: "a1",
    title: "Possible Pipeline Burst in Sector 5",
    description: "Water complaints increased 400% in the last 2 hours",
    severity: "critical",
    affected_population: 300,
    timestamp: "10 min ago",
  },
  {
    id: "a2",
    title: "High Impact Pothole Detected",
    description: "Near Government School — heavy traffic area",
    severity: "warning",
    affected_population: 150,
    timestamp: "25 min ago",
  },
  {
    id: "a3",
    title: "Streetlight Cluster Failure",
    description: "4 streetlights out in a 200m radius on NH-8",
    severity: "warning",
    affected_population: 500,
    timestamp: "1 hour ago",
  },
];

export const mockIssues: Issue[] = [
  {
    id: "i1",
    title: "Large Pothole Near Government School",
    description:
      "Large pothole near Government School causing traffic disruptions and posing risk to two-wheelers.",
    category: "road_damage",
    severity: "high",
    status: "verified",
    priority_score: 92,
    confidence: 94,
    affected_citizens: 42,
    verification_count: 17,
    latitude: 28.6139,
    longitude: 77.209,
    address: "Sector 5, Near Government School",
    image_url: "/placeholder-pothole.jpg",
    created_at: "2026-06-22T10:30:00Z",
    updated_at: "2026-06-23T08:15:00Z",
    root_cause: "Heavy monsoon rain + poor drainage",
    root_cause_confidence: 88,
    similar_cases: 15,
    timeline: [
      {
        id: "t1",
        type: "reported",
        description: "Issue first reported",
        timestamp: "2026-06-22T10:30:00Z",
      },
      {
        id: "t2",
        type: "citizens_increased",
        description: "Affected citizens increased to 20",
        timestamp: "2026-06-22T14:00:00Z",
      },
      {
        id: "t3",
        type: "priority_increased",
        description: "Priority raised to High",
        timestamp: "2026-06-22T18:00:00Z",
      },
      {
        id: "t4",
        type: "verified",
        description: "Community verified by 17 citizens",
        timestamp: "2026-06-23T08:15:00Z",
      },
    ],
  },
  {
    id: "i2",
    title: "Water Pipeline Failure",
    description:
      "Major water pipeline burst causing flooding in residential area. Multiple households affected.",
    category: "water",
    severity: "critical",
    status: "reported",
    priority_score: 97,
    confidence: 89,
    affected_citizens: 156,
    verification_count: 23,
    latitude: 28.615,
    longitude: 77.211,
    address: "Sector 5, Block B",
    created_at: "2026-06-23T06:00:00Z",
    updated_at: "2026-06-23T10:00:00Z",
    root_cause: "Aging infrastructure",
    root_cause_confidence: 82,
    similar_cases: 8,
    timeline: [
      {
        id: "t1",
        type: "reported",
        description: "Pipe burst reported",
        timestamp: "2026-06-23T06:00:00Z",
      },
      {
        id: "t2",
        type: "citizens_increased",
        description: "Affected citizens surged to 156",
        timestamp: "2026-06-23T08:00:00Z",
      },
    ],
  },
  {
    id: "i3",
    title: "Overflowing Garbage Bin at Market",
    description: "Garbage bin at Main Market overflowing for 3 days. Attracting stray animals.",
    category: "waste",
    severity: "medium",
    status: "verified",
    priority_score: 68,
    confidence: 91,
    affected_citizens: 85,
    verification_count: 12,
    latitude: 28.618,
    longitude: 77.205,
    address: "Main Market, Shop No. 45",
    created_at: "2026-06-20T09:00:00Z",
    updated_at: "2026-06-23T07:00:00Z",
    root_cause: "Delayed municipal pickup schedule",
    root_cause_confidence: 76,
    similar_cases: 22,
    timeline: [
      {
        id: "t1",
        type: "reported",
        description: "Garbage overflow reported",
        timestamp: "2026-06-20T09:00:00Z",
      },
      {
        id: "t2",
        type: "verified",
        description: "Verified by 12 citizens",
        timestamp: "2026-06-21T15:00:00Z",
      },
    ],
  },
  {
    id: "i4",
    title: "Streetlight Out on Park Road",
    description: "Streetlight non-functional for a week. Dark stretch creating safety concerns.",
    category: "lighting",
    severity: "medium",
    status: "reported",
    priority_score: 72,
    confidence: 87,
    affected_citizens: 35,
    verification_count: 8,
    latitude: 28.612,
    longitude: 77.208,
    address: "Park Road, Near Community Center",
    created_at: "2026-06-19T18:00:00Z",
    updated_at: "2026-06-22T20:00:00Z",
    root_cause: "Electrical fault",
    root_cause_confidence: 91,
    similar_cases: 5,
    timeline: [
      {
        id: "t1",
        type: "reported",
        description: "Streetlight outage reported",
        timestamp: "2026-06-19T18:00:00Z",
      },
    ],
  },
  {
    id: "i5",
    title: "Blocked Storm Drain",
    description:
      "Storm drain blocked with debris causing water logging during rain. Road becomes impassable.",
    category: "drainage",
    severity: "high",
    status: "in_progress",
    priority_score: 85,
    confidence: 92,
    affected_citizens: 67,
    verification_count: 14,
    latitude: 28.616,
    longitude: 77.213,
    address: "Sector 7, Ring Road Junction",
    created_at: "2026-06-21T11:00:00Z",
    updated_at: "2026-06-23T09:00:00Z",
    root_cause: "Blocked drain + construction debris",
    root_cause_confidence: 85,
    similar_cases: 11,
    timeline: [
      {
        id: "t1",
        type: "reported",
        description: "Blocked drain reported",
        timestamp: "2026-06-21T11:00:00Z",
      },
      {
        id: "t2",
        type: "citizens_increased",
        description: "Affected citizens grew to 67",
        timestamp: "2026-06-22T16:00:00Z",
      },
      {
        id: "t3",
        type: "priority_increased",
        description: "Priority elevated due to monsoon forecast",
        timestamp: "2026-06-23T09:00:00Z",
      },
    ],
  },
  {
    id: "i6",
    title: "Broken Footpath Tiles",
    description: "Multiple broken tiles on footpath causing tripping hazard for pedestrians.",
    category: "road_damage",
    severity: "low",
    status: "reported",
    priority_score: 45,
    confidence: 78,
    affected_citizens: 18,
    verification_count: 5,
    latitude: 28.61,
    longitude: 77.207,
    address: "Sector 3, Main Walkway",
    created_at: "2026-06-22T14:00:00Z",
    updated_at: "2026-06-22T14:00:00Z",
    timeline: [
      {
        id: "t1",
        type: "reported",
        description: "Broken tiles reported",
        timestamp: "2026-06-22T14:00:00Z",
      },
    ],
  },
  {
    id: "i7",
    title: "Open Manhole Near Metro Gate",
    description:
      "Open manhole cover at the metro exit edge is creating a severe pedestrian hazard during peak commute hours.",
    category: "safety",
    severity: "critical",
    status: "verified",
    priority_score: 96,
    confidence: 93,
    affected_citizens: 118,
    verification_count: 31,
    latitude: 28.6115,
    longitude: 77.2145,
    address: "Metro Gate 2, Sector 6",
    created_at: "2026-06-23T05:20:00Z",
    updated_at: "2026-06-23T11:00:00Z",
    root_cause: "Loose utility access cover",
    root_cause_confidence: 84,
    similar_cases: 6,
    timeline: [
      {
        id: "t1",
        type: "reported",
        description: "Open manhole reported",
        timestamp: "2026-06-23T05:20:00Z",
      },
      {
        id: "t2",
        type: "verified",
        description: "Verified by commuters",
        timestamp: "2026-06-23T07:45:00Z",
      },
    ],
  },
  {
    id: "i8",
    title: "Illegal Dumping Behind Clinic",
    description:
      "Construction debris and household waste have been dumped behind the clinic, blocking the service lane.",
    category: "waste",
    severity: "high",
    status: "reported",
    priority_score: 81,
    confidence: 86,
    affected_citizens: 64,
    verification_count: 9,
    latitude: 28.6195,
    longitude: 77.2098,
    address: "Civil Clinic Service Lane",
    created_at: "2026-06-22T16:10:00Z",
    updated_at: "2026-06-23T09:35:00Z",
    root_cause: "Unmonitored dumping point",
    root_cause_confidence: 72,
    similar_cases: 13,
    timeline: [
      {
        id: "t1",
        type: "reported",
        description: "Dumping point reported",
        timestamp: "2026-06-22T16:10:00Z",
      },
    ],
  },
  {
    id: "i9",
    title: "Low Water Pressure in Tower C",
    description:
      "Residents are reporting low water pressure on upper floors for the third consecutive morning.",
    category: "water",
    severity: "medium",
    status: "in_progress",
    priority_score: 74,
    confidence: 88,
    affected_citizens: 92,
    verification_count: 18,
    latitude: 28.6171,
    longitude: 77.216,
    address: "Tower C, Sector 7 Apartments",
    created_at: "2026-06-21T07:30:00Z",
    updated_at: "2026-06-23T06:50:00Z",
    root_cause: "Pump pressure fluctuation",
    root_cause_confidence: 81,
    similar_cases: 9,
    timeline: [
      {
        id: "t1",
        type: "reported",
        description: "Low pressure reported",
        timestamp: "2026-06-21T07:30:00Z",
      },
      {
        id: "t2",
        type: "priority_increased",
        description: "Priority raised after repeat reports",
        timestamp: "2026-06-23T06:50:00Z",
      },
    ],
  },
  {
    id: "i10",
    title: "Loose Electric Wire on Service Road",
    description:
      "A loose overhead wire is hanging close to vehicles and pedestrians near the service road turn.",
    category: "lighting",
    severity: "critical",
    status: "reported",
    priority_score: 95,
    confidence: 90,
    affected_citizens: 73,
    verification_count: 15,
    latitude: 28.6089,
    longitude: 77.2118,
    address: "NH-8 Service Road Turn",
    created_at: "2026-06-23T08:10:00Z",
    updated_at: "2026-06-23T10:45:00Z",
    root_cause: "Storm damage to utility pole",
    root_cause_confidence: 77,
    similar_cases: 4,
    timeline: [
      {
        id: "t1",
        type: "reported",
        description: "Loose wire reported",
        timestamp: "2026-06-23T08:10:00Z",
      },
    ],
  },
  {
    id: "i11",
    title: "Loud Construction After Hours",
    description:
      "Construction noise is continuing past permitted hours and disturbing nearby residential blocks.",
    category: "noise",
    severity: "low",
    status: "verified",
    priority_score: 52,
    confidence: 82,
    affected_citizens: 40,
    verification_count: 11,
    latitude: 28.6147,
    longitude: 77.2028,
    address: "Market Square Redevelopment Site",
    created_at: "2026-06-22T22:00:00Z",
    updated_at: "2026-06-23T00:30:00Z",
    root_cause: "After-hours contractor activity",
    root_cause_confidence: 69,
    similar_cases: 7,
    timeline: [
      {
        id: "t1",
        type: "reported",
        description: "Noise complaint reported",
        timestamp: "2026-06-22T22:00:00Z",
      },
      {
        id: "t2",
        type: "verified",
        description: "Verified by residents",
        timestamp: "2026-06-23T00:30:00Z",
      },
    ],
  },
  {
    id: "i12",
    title: "Faded Zebra Crossing",
    description:
      "Pedestrian crossing markings have faded near the school gate, making morning crossings unsafe.",
    category: "road_damage",
    severity: "medium",
    status: "reported",
    priority_score: 66,
    confidence: 80,
    affected_citizens: 58,
    verification_count: 7,
    latitude: 28.6208,
    longitude: 77.2069,
    address: "School Gate, Sector 4",
    created_at: "2026-06-20T08:15:00Z",
    updated_at: "2026-06-22T12:20:00Z",
    root_cause: "Road markings worn by traffic",
    root_cause_confidence: 74,
    similar_cases: 12,
    timeline: [
      {
        id: "t1",
        type: "reported",
        description: "Crossing repaint requested",
        timestamp: "2026-06-20T08:15:00Z",
      },
    ],
  },
];

export const mockProfile: UserProfile = {
  id: "u1",
  name: "Utsav",
  impact_score: 847,
  reports_created: 23,
  issues_verified: 67,
  people_helped: 1240,
  title: "Community Guardian",
  recent_activity: [
    {
      id: "ra1",
      action: "verified",
      issue_title: "Large Pothole Near Government School",
      timestamp: "2 hours ago",
    },
    {
      id: "ra2",
      action: "reported",
      issue_title: "Streetlight Out on Park Road",
      timestamp: "Yesterday",
    },
    {
      id: "ra3",
      action: "marked resolved",
      issue_title: "Garbage Overflow at Bus Stop",
      timestamp: "2 days ago",
    },
    {
      id: "ra4",
      action: "verified",
      issue_title: "Blocked Storm Drain",
      timestamp: "3 days ago",
    },
  ],
};

export const mockCityMood: CityMood = {
  summary: [
    "Road conditions improving across most sectors.",
    "Water complaints increased 18% — concentrated in Sector 5.",
    "18 issues resolved today — above weekly average.",
    "Streetlights have the fastest resolution rate at 2.3 days.",
  ],
  generated_at: "2026-06-23T10:00:00Z",
};

export const mockInsights: PredictiveInsight[] = [
  {
    id: "pi1",
    description: "Streetlight failures tend to rise 40% during monsoon season.",
    confidence: 87,
    category: "lighting",
  },
  {
    id: "pi2",
    description: "Garbage complaints typically increase 25% after festivals.",
    confidence: 82,
    category: "waste",
  },
  {
    id: "pi3",
    description: "Water shortages have been recurring every Friday in Sector 5.",
    confidence: 79,
    category: "water",
  },
  {
    id: "pi4",
    description: "Drainage issues spike 3 days after heavy rainfall events.",
    confidence: 91,
    category: "drainage",
  },
];
